config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :users
  resources :politicians

  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  root to: 'sessions#new'
  get '/register' => 'users#new', as: '/register'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
	belongs_to :politician
end

app/models/concerns/gather_bills.rb
class GatherBills

	attr_reader :politicians

  def initialize(politicians)
  	@politicians = [politicians].flatten
  end

  def run
    results = @politicians.map {|polit| {polit => get_bills(polit)} }
  end

  def get_bills(politician)
    client = Adapter::Bills.new  
    politician.bills.destroy_all
		Bill.create(client.run(politician))
  end


end

app/models/district.rb
class District < ApplicationRecord
	has_many :users
	belongs_to :state
	has_many :politicians
end

app/models/message.rb
class Message < ApplicationRecord

	belongs_to :user
	belongs_to :politician

end

app/models/politician.rb
class Politician < ApplicationRecord
  has_many :messages
  belongs_to :state
  belongs_to :district
  has_many :bills

  include ActionView::Helpers::DateHelper

  def image_name
    [first_name.capitalize, last_name.capitalize + '.jpg'].join('_')
  end

  def senate
    "Member of the United States Senate representing the State of #{state.name}"
  end

  def house
    "Member of the United States House of Representatives from #{state.name}'s
      #{district.name.to_i.ordinalize} district"
  end

  def house_or_senate
    self.district.nil? ? senate : house
  end

  def age
    distance_of_time_in_words(Date.today.to_time - birthday.to_date.to_time).capitalize
  end

  def full_name
    [first_name, middle_name, last_name].compact.join(' ')
  end

  def first_last
    [first_name, last_name].compact.join(' ')
  end

  FILTER_BY = ['Senators','House of Reps','Democrat','Republican','Has Youtube', 
    'Has Facebook','Has Twitter','Social Gurus', 'All']
  ##QUERIES ADD ^ HERE

  SEARCH_HASH = {
    'Over (Age)' => 'polit_over_age',
    'Under (Age)' => 'polit_under_age',
    'By (Age)' => 'polit_by_age',
    'By (Name)' => 'search_name'
  }

  def self.search_name(name)
    where('last_name = ? OR first_name = ?',"#{last_name}","#{first_name}")
  end

  def self.republican
    where(party: 'R')
  end

  def self.democrat
    where(party: 'D')
  end

  def self.house_of_reps
    where(chamber: "house")
  end

  def self.senators
    where(chamber: "senate")
  end

  def self.polit_over_age(age)
    where('birthday < ?',"#{Time.now.year - age.to_i}")
  end

  def self.polit_under_age(age)
    where('birthday > ?',"#{Time.now.year - age.to_i}")
  end

  def self.polit_by_age(age)
    where('birthday = ?',"#{Time.now.year - age.to_i}")
  end

  def self.has_youtube
    where.not(youtube: nil)
  end

  def self.has_facebook
    where.not(facebook: nil)
  end

  def self.has_twitter
    where.not(twitter: nil)
  end

  def self.social_gurus
    has_twitter.has_youtube.has_facebook
  end

end

app/models/state.rb
class State < ApplicationRecord
	has_many :users
	has_many :politicians
	has_many :districts

  scope :ordered, -> { order :name }
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  
  belongs_to :district
  belongs_to :state
  has_many :messages

  # validates :email, presence: true, uniqueness: trues
  # validates_presence_of :password, :street_address, :state, :city, :first_name, :last_name

  def name
  	first_name + ' ' + last_name
  end

  def representative
    district.politicians.first
  end

  def senior_sen
    state.politicians.where(chamber: 'senate').where(state_rank: 'senior').first
  end

  def junior_sen
    state.politicians.where(chamber: 'senate').where(state_rank: 'junior').first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception
  before_action :login_required
  helper_method :current_user, :logged_in?

  def current_user
    User.where(id: session[:user_id]).first if session[:user_id]
  end

  def login(user)
    session[:user_id] = @user.id
  end

  def logged_in?
    !!current_user
  end

  def login_required
    redirect_to root_path if !logged_in?
  end



end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
	

	def new
		binding.pry
		@bill = Bill.new
	end

	def create

	end



	private 

	def bills_params
	end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def new
		@message = Message.new
	end

	def create
		@message = Message.new(message_params)
		# @message.subject = params[:message][:subject]
		# @message.content = params[:message][:content]
		@message.user_id = session[:user_id]
		@message.politician_id = request.referer[34..-1].to_i
		@message.save
		PoliticianMailer.send_email(@message).deliver
		flash[:alert] = "Message successfully created"
		redirect_to politician_path(Politician.find_by(id: @message.politician_id))
	end

	private

	def message_params
		 params.require(:message).permit(:subject, :content)
	end
end

app/controllers/politicians_controller.rb
class PoliticiansController < ApplicationController

  def show
    @politician = Politician.find(params[:id])
  end

  def index
    if params['query'].nil?
      @politicians = Politician.order('Random()').first(9)
    else
      @politicians = search.first(9)
    end
  end

  private

  def query_params
    params.require(:query).permit(:search_value, :search_by, search_filter: [])
  end

  def search_method
    query_params.values[1]
  end

  def search_value
    query_params.values[0].capitalize
  end

  def filter_method
    query_params.values[2].map(&:downcase).map {|value| value.split.join('_')} if !query_params.values[2].nil?
  end

  def search
    if search_method.nil?
      send_chain 
    elsif filter_method.nil?
      Politician.send(search_method,search_value)
    else
      send_chain.send(search_method,search_value)
    end
  end

  def send_chain
    filter_method.inject(Politician) {|polit,filter| polit.send(filter)}
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    if logged_in?
      session[:user_id] = nil
      flash.now[:message] = 'You have been logged out'
    end
  end


  def create
    user = User.find_by(email: params[:user][:email])
    if user == nil
      flash.now[:message] = 'A user with that email address does not exist. Please create an account.'
      render 'new'
    elsif user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to user_path(session[:user_id])
    else
      flash.now[:message] = 'Please enter the correct password'
      render 'new'
    end
  end


  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  # before_action :ensure_user_is_current, only: :show

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    Adapter::Districts.new(@user)
    if @user.save
      login(@user)
      flash[:message] = 'Welcome to Know Your Rep! You have successfully created an account.'
      redirect_to user_path(@user)
    else
      flash.now[:message] = @user.errors.full_messages
      render register_path
    end
  end

  def show
    @user = User.find params[:id]
  end

  def update

  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :street_address, :city, :password, :email, :state_id)
  end

  # def ensure_user_is_current
  #   redirect_to root_url unless params[:id].to_i == current_user.id
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/politicians_helper.rb
module PoliticiansHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bills/_bill.html.erb
<p><%= link_to bill.title, bill.url %> Co-Sponsor Count:<%= bill.cosponsor_count %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Know My Rep</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<body>
  <div class="container">

  <div class="navbar">
  <ul class="nav nav-pills">
  <% if !current_user.nil? %>
  <li role="presentation" class="navbutton"><a href=<%= user_path(current_user)%>>My Homepage</a></li>
  <li role="presentation" class="navbutton"><a href=<%= politicians_path%>>Politicians</a></li>
  <li role="presentation" class="navbutton"><a href=<%= logout_path%>>Log Out</a></li>
  <% else %>  
    <li role="presentation" class="navbutton"><a href=<%= register_path%>>Sign Up</a></li>
    <li role="presentation" class="navbutton"><a href=<%= root_path%>>Log In</a></li>
  <% end %>
  </ul>
  </div>

  <%= yield %>

  </div>

</body>
</html>

app/views/messages/_form.html.erb
<div class="form-horizontal col-xs-9">
<%= form_for(Message.new, html: {class: 'form-horizontal'}) do |f| %>
  <div class="field form-group">
	  <p><%= f.label :subject, class: 'col-sm-2 control-label' %></p>
	  <div class="col-sm-10">
	  <p><%= f.text_field :subject, class: 'form-control' %></p>
	  </div>
  </div>
  <div class="field form-group">
  <p><%= f.label :content, class: 'col-sm-2 control-label' %></p>
  <div class="col-sm-10">
  <p><%= f.text_area :content, class: 'form-control' %></p>
  </div>
  </div>
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10"> 
  <p><%= f.submit 'Send Message' %> </p>
   </div>
  </div>
<% end %>

app/views/politicians/_politician.html.erb
<div class="thumbnail panel panel-default col-xs-3 colspace whitebox shadow">
  <div class="panel-body img-rounded img-responsive">
    <div class="img-rounded"> <%= link_to image_tag("#{politician.image_name}"), politician_path(politician) %></div>
    <div><h3><%= link_to politician.first_last, politician_path(politician)  %></h3></div>
      <div><%= '(' + politician.party + '.) ' +  politician.chamber.capitalize %></div>
    </div>
</div>

app/views/politicians/_politician_bills.html.erb
<div class="panel panel-default col-xs-4 whitebox shadow">
  <div class="panel-body">
  
    <% politician.bills.each do |bill|  %>
    	<p><%= link_to bill.title, bill.url %></p>
    <% end %>
    </div>
</div>

app/views/politicians/_politician_profile.html.erb
<div class="panel panel-default col-xs-3 hero-feature whitebox shadow">
  <div class="thumbnail">
  <% image_url = "/assets/#{politician.image_name}" %>
      <img src=<%="#{image_url}"%> alt=""></div>
      <div class="caption">
          <div><h3><%= politician.full_name  %></h3></div>
          <div><h4><%= politician.house_or_senate %></h4></div>
          <div>Age: <%= politician.age %></div>
          <div>Prior Experience: </div>
          <div>Education:</div>
          <br>
          <div><a class="btn btn-lg btn-twitter" target="_blank" href="https://twitter.com/<%= politician.twitter %>">
            <span class="fa fa-twitter"></span>
          </a>
          <a class="btn btn-lg btn-facebook" target="_blank" href="https://facebook.com/<%= politician.facebook %>">
            <span class="fa fa-facebook"></span>
          </a>
          <a class="btn btn-lg btn-primary" target="_blank" href="https://www.youtube.com/user/<%= politician.youtube %>">
            <span class="fa fa-youtube"></span>
          </a>
          </div>
      </div>
  <br>
</div>

app/views/politicians/index.html.erb
<h3>Query All Politicians:</h3>
<%= form_tag '/politicians', method: "GET" do %>
<div>Search by:<%= select_tag "query[search_by]", options_for_select(Politician::SEARCH_HASH)%>
Value: <%= text_field_tag "query[search_value]" %>
Filter By: <%= select_tag "query[search_filter][]", options_for_select(Politician::FILTER_BY), multiple: true %>


<%= submit_tag 'Search' %></div>
<% end %>


<h1>Politicians</h1>
<br>


<%= render @politicians %>

app/views/politicians/show.html.erb
<br>
<br>
<div class="row" >
  <%= render "politician_profile", politician: @politician %>
  <div class="bills col-md-9 col-sm-6 whitebox shadow">
    <h3>Bills</h3>
      <%= render @politician.bills %>
    </div>
    <div class="message col-md-9 col-sm-6 whitebox shadow">
      <h3>Send a Message</h3>
      <%= render partial: "messages/form" %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% if !flash[:message].nil? %>
<% flash[:message].each do |message| %>
  <ul>
    <li><%= message %></li>
  </ul>
  <% end %>
  <% end %>


<h3>Please create your account below</h3>

<%= form_for @user do |f| %>
  <p><%= f.label :email %></p>
  <p><%= f.text_field :email %></p>
  <p><%= f.label :password %></p>
  <p><%= f.password_field :password %></p>
  <p><%= f.label :first_name %></p>
  <p><%= f.text_field :first_name %></p>
  <p><%= f.label :last_name %></p>
  <p><%= f.text_field :last_name %></p>
  <p><%= f.label :street_address %></p>
  <p><%= f.text_field :street_address %></p>
  <p><%= f.label :city %></p>
  <p><%= f.text_field :city %></p>
  <p><%= f.label :state %></p>
  <p><%= f.collection_select :state_id, State.ordered, :id, :name %></p>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<div class="panel panel-default hero-feature whitebox shadow">
<div class="panel-body">
<div><h3><%= @user.name %></h3></div>
<div><%= "#{@user.street_address}, #{@user.city}, #{@user.district.state.name}" %></div>
</div>
</div>

<h3>Your Representatives</h3>

    <div id="main-container" class="container-fluid">
      <div class="row">
      <br>
      <br>
          <%= render @user.representative %>
          <%= render @user.senior_sen %>
          <%= render @user.junior_sen %>
        
    </div>
    </div>
  <br>